"""atualiza tabela usuario

Revision ID: 1aee280a2f5b
Revises: a331308760f5
Create Date: 2026-08-22 09:25:23.395398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aee280a2f5b'
down_revision: Union[str, Sequence[str], None] = 'a331308760f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'usuario', ['celular'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    # ### end Alembic commands ###
