"""cria tabelas carrinho

Revision ID: 3e3363927469
Revises: c9bcdca5ab63
Create Date: 2026-09-22 08:44:10.745122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3363927469'
down_revision: Union[str, Sequence[str], None] = 'c9bcdca5ab63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrinho',
    sa.Column('id_carrinho', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_restaurante', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_restaurante'], ['restaurante.id_restaurante'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_carrinho')
    )
    op.create_index(op.f('ix_carrinho_id_restaurante'), 'carrinho', ['id_restaurante'], unique=False)
    op.create_index(op.f('ix_carrinho_id_usuario'), 'carrinho', ['id_usuario'], unique=False)
    op.create_index("uq_carrinho_usuario_ativo","carrinho",["id_usuario"],unique=True,postgresql_where=sa.text("status = 'ATIVO'"),)
    op.create_table('carrinho_item',
    sa.Column('id_item', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_carrinho', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_carrinho'], ['carrinho.id_carrinho'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id_produto'], ),
    sa.PrimaryKeyConstraint('id_item')
    )
    op.create_index(op.f('ix_carrinho_item_id_carrinho'), 'carrinho_item', ['id_carrinho'], unique=False)
    op.create_index(op.f('ix_carrinho_item_id_produto'), 'carrinho_item', ['id_produto'], unique=False)
    op.create_table('carrinho_item_complemento',
    sa.Column('id_item_complemento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_item', sa.Integer(), nullable=False),
    sa.Column('id_complemento', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_complemento'], ['complemento.id_complemento'], ),
    sa.ForeignKeyConstraint(['id_item'], ['carrinho_item.id_item'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_item_complemento')
    )
    op.create_index(op.f('ix_carrinho_item_complemento_id_complemento'), 'carrinho_item_complemento', ['id_complemento'], unique=False)
    op.create_index(op.f('ix_carrinho_item_complemento_id_item'), 'carrinho_item_complemento', ['id_item'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carrinho_item_complemento_id_item'), table_name='carrinho_item_complemento')
    op.drop_index(op.f('ix_carrinho_item_complemento_id_complemento'), table_name='carrinho_item_complemento')
    op.drop_table('carrinho_item_complemento')
    op.drop_index(op.f('ix_carrinho_item_id_produto'), table_name='carrinho_item')
    op.drop_index(op.f('ix_carrinho_item_id_carrinho'), table_name='carrinho_item')
    op.drop_table('carrinho_item')
    op.drop_index("uq_carrinho_usuario_ativo",table_name="carrinho",)
    op.drop_index(op.f('ix_carrinho_id_usuario'), table_name='carrinho')
    op.drop_index(op.f('ix_carrinho_id_restaurante'), table_name='carrinho')
    op.drop_table('carrinho')
    # ### end Alembic commands ###
