"""cria endereco restaurante

Revision ID: 428461dd32e3
Revises: 510428c855c9
Create Date: 2026-09-10 16:16:12.830800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428461dd32e3'
down_revision: Union[str, Sequence[str], None] = '510428c855c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endereco_restaurante',
    sa.Column('id_endereco_restaurante', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_restaurante', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('logradouro', sa.String(length=50), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('complemento', sa.String(length=50), nullable=True),
    sa.Column('bairro', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('ponto_referencia', sa.String(length=70), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_restaurante'], ['restaurante.id_restaurante'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_endereco_restaurante')
    )
    op.create_index(op.f('ix_endereco_restaurante_cep'), 'endereco_restaurante', ['cep'], unique=False)
    op.create_index(op.f('ix_endereco_restaurante_id_restaurante'), 'endereco_restaurante', ['id_restaurante'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endereco_restaurante_id_restaurante'), table_name='endereco_restaurante')
    op.drop_index(op.f('ix_endereco_restaurante_cep'), table_name='endereco_restaurante')
    op.drop_table('endereco_restaurante')
    # ### end Alembic commands ###
