"""remove categoria do restaurante

Revision ID: 510428c855c9
Revises: e5d732f22295
Create Date: 2026-09-09 14:07:42.739386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '510428c855c9'
down_revision: Union[str, Sequence[str], None] = 'e5d732f22295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurante', 'categoria')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column(
        "restaurante",
        sa.Column(
            "categoria",
            sa.String(length=50),
            nullable=True,
        ),
    )