"""adiciona cascade responsavel restaurante

Revision ID: 9472c646ffa9
Revises: 428461dd32e3
Create Date: 2026-09-12 13:10:55.293707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9472c646ffa9'
down_revision: Union[str, Sequence[str], None] = '428461dd32e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('restaurante_responsavel_id_fkey'), 'restaurante', type_='foreignkey')
    op.create_foreign_key(None, 'restaurante', 'responsavel_restaurante', ['responsavel_id'], ['id_responsavel'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurante', type_='foreignkey')
    op.create_foreign_key(op.f('restaurante_responsavel_id_fkey'), 'restaurante', 'responsavel_restaurante', ['responsavel_id'], ['id_responsavel'])
    # ### end Alembic commands ###
