"""cria tabela cardapio

Revision ID: b76a6c5da439
Revises: f086a5132a1c
Create Date: 2026-09-14 10:49:12.151948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b76a6c5da439'
down_revision: Union[str, Sequence[str], None] = 'f086a5132a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardapio',
    sa.Column('id_cardapio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_restaurante', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_restaurante'], ['restaurante.id_restaurante'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_cardapio')
    )
    op.create_index(op.f('ix_cardapio_id_restaurante'), 'cardapio', ['id_restaurante'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cardapio_id_restaurante'), table_name='cardapio')
    op.drop_table('cardapio')
    # ### end Alembic commands ###
