"""cria tabela categorias_restaurante

Revision ID: c7dabc4f51ea
Revises: 2b3c4d5e6f7a
Create Date: 2026-09-03 09:42:59.642297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7dabc4f51ea'
down_revision: Union[str, Sequence[str], None] = '2b3c4d5e6f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='ATIVA', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_categoria_created_at', 'categoria', ['created_at'], unique=False)
    op.create_index('idx_categoria_status', 'categoria', ['status'], unique=False)
    op.create_index('uq_categoria_nome', 'categoria', [sa.literal_column('lower(nome)')], unique=True)
    op.drop_constraint(op.f('ck_endereco_cep_oito_digitos'), 'endereco', type_='check')
    op.drop_constraint(op.f('ck_endereco_uf_duas_letras'), 'endereco', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_endereco_uf_duas_letras'), 'endereco', "uf::text ~ '^[A-Z]{2}$'::text")
    op.create_check_constraint(op.f('ck_endereco_cep_oito_digitos'), 'endereco', "cep::text ~ '^[0-9]{8}$'::text")
    op.drop_index('uq_categoria_nome', table_name='categoria')
    op.drop_index('idx_categoria_status', table_name='categoria')
    op.drop_index('idx_categoria_created_at', table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###
