"""cria tabela restaurante categoria

Revision ID: e5d732f22295
Revises: 0f26a48edb4c
Create Date: 2026-09-09 09:49:52.924360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d732f22295'
down_revision: Union[str, Sequence[str], None] = '0f26a48edb4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurante_categoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id_restaurante'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurante_id', 'categoria_id', name='uq_restaurante_categoria')
    )
    op.create_index('idx_rc_categoria_id', 'restaurante_categoria', ['categoria_id'], unique=False)
    op.create_index('idx_rc_restaurante_id', 'restaurante_categoria', ['restaurante_id'], unique=False)
    op.drop_constraint(op.f('uq_canal_venda_restaurante_tipo'), 'canal_venda', type_='unique')
    op.drop_constraint(op.f('ck_canal_venda_tipo_valido'), 'canal_venda', type_='check')
    op.drop_constraint(op.f('ck_horario_funcionamento_dia_semana_valido'), 'horario_funcionamento', type_='check')
    op.drop_constraint(op.f('ck_horario_funcionamento_intervalo_valido'), 'horario_funcionamento', type_='check')
    op.drop_constraint(op.f('responsavel_restaurante_celular_key'), 'responsavel_restaurante', type_='unique')
    op.drop_constraint(op.f('responsavel_restaurante_email_key'), 'responsavel_restaurante', type_='unique')
    op.drop_index(op.f('ix_responsavel_restaurante_celular'), table_name='responsavel_restaurante')
    op.create_index(op.f('ix_responsavel_restaurante_celular'), 'responsavel_restaurante', ['celular'], unique=True)
    op.drop_index(op.f('ix_responsavel_restaurante_email'), table_name='responsavel_restaurante')
    op.create_index(op.f('ix_responsavel_restaurante_email'), 'responsavel_restaurante', ['email'], unique=True)
    op.drop_constraint(op.f('restaurante_cnpj_key'), 'restaurante', type_='unique')
    op.drop_index(op.f('ix_restaurante_cnpj'), table_name='restaurante')
    op.create_index(op.f('ix_restaurante_cnpj'), 'restaurante', ['cnpj'], unique=True)
    op.drop_constraint(op.f('ck_restaurante_cnpj_quatorze_digitos'), 'restaurante', type_='check')
    op.drop_constraint(op.f('ck_restaurante_status_valido'), 'restaurante', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_restaurante_status_valido'), 'restaurante', "status::text = ANY (ARRAY['PENDENTE'::character varying, 'DISPONIVEL'::character varying, 'INATIVO'::character varying]::text[])")
    op.create_check_constraint(op.f('ck_restaurante_cnpj_quatorze_digitos'), 'restaurante', "cnpj::text ~ '^[0-9]{14}$'::text")
    op.drop_index(op.f('ix_restaurante_cnpj'), table_name='restaurante')
    op.create_index(op.f('ix_restaurante_cnpj'), 'restaurante', ['cnpj'], unique=False)
    op.create_unique_constraint(op.f('restaurante_cnpj_key'), 'restaurante', ['cnpj'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_responsavel_restaurante_email'), table_name='responsavel_restaurante')
    op.create_index(op.f('ix_responsavel_restaurante_email'), 'responsavel_restaurante', ['email'], unique=False)
    op.drop_index(op.f('ix_responsavel_restaurante_celular'), table_name='responsavel_restaurante')
    op.create_index(op.f('ix_responsavel_restaurante_celular'), 'responsavel_restaurante', ['celular'], unique=False)
    op.create_unique_constraint(op.f('responsavel_restaurante_email_key'), 'responsavel_restaurante', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('responsavel_restaurante_celular_key'), 'responsavel_restaurante', ['celular'], postgresql_nulls_not_distinct=False)
    op.create_check_constraint(op.f('ck_horario_funcionamento_intervalo_valido'), 'horario_funcionamento', 'hora_abertura < hora_fechamento')
    op.create_check_constraint(op.f('ck_horario_funcionamento_dia_semana_valido'), 'horario_funcionamento', "dia_semana::text = ANY (ARRAY['SEGUNDA'::character varying, 'TERCA'::character varying, 'QUARTA'::character varying, 'QUINTA'::character varying, 'SEXTA'::character varying, 'SABADO'::character varying, 'DOMINGO'::character varying]::text[])")
    op.create_check_constraint(op.f('ck_canal_venda_tipo_valido'), 'canal_venda', "tipo::text = ANY (ARRAY['ENTREGA'::character varying, 'RETIRADA'::character varying]::text[])")
    op.create_unique_constraint(op.f('uq_canal_venda_restaurante_tipo'), 'canal_venda', ['id_restaurante', 'tipo'], postgresql_nulls_not_distinct=False)
    op.drop_index('idx_rc_restaurante_id', table_name='restaurante_categoria')
    op.drop_index('idx_rc_categoria_id', table_name='restaurante_categoria')
    op.drop_table('restaurante_categoria')
    # ### end Alembic commands ###
